### ISSUE TITLE
Binding piwikTracker library error libswiftCore.dylib Xamarin

### ISSUE THREAD

**Issue by domdp16** [Flash3001/Xamarin.Swift#14]
Hi Lucas,
i create the binding about piwikTracker library write in Swift and integrated the dll in xamarin project, in debug everything works.

But when i create the ipa for release mode, when launched the app crashed.

Below the error:

Launched application on 'iPhone' with pid 2234 Application terminated. dyld: Library not loaded: @rpath/libswiftCore.dylib Referenced from: /private/var/containers/Bundle/Application/75ABA1AA-2240-45F2-A224-A5BB4E947549/APP/Frameworks/PiwikTracker.framework/PiwikTracker Reason: image not found

How can i solve the problem??

Many thanks

**Comment by Flash3001** [comment]
Hey @domdp16 did you include all the needed Swift libraries to the iOS App project? The error message says there is a native library missing, but it doesn't say which one. 

Let's try this to see if the that is the problem: Include all 40 Swift (4 or 3) library packages and run again. If that fix the problem we now that it is one of them that is missing. 

note: It is not a good idea to publish the app with all libraries included, as they are huge.

**Comment by domdp16** [comment]
Hi Lucas, thanks a lot for the answar.
I tried to install the app with all libraries but the app crashed (now in debug too). Below the error message:

Launched application on 'iPhone' with pid 3811
dyld: Symbol not found: __T0s11_StringCoreV22isRepresentableAsASCIISbyFSbs6UInt16VcfU_
  Referenced from: /private/var/containers/Bundle/Application/CAF3AC68-BD88-4478-BDD8-DAAE068C37BD/APP.iOS.app/Frameworks/PiwikTracker.framework/PiwikTracker
  Expected in: /private/var/containers/Bundle/Application/CAF3AC68-BD88-4478-BDD8-DAAE068C37BD/APP.iOS.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/CAF3AC68-BD88-4478-BDD8-DAAE068C37BD/APP.iOS.app/Frameworks/PiwikTracker.framework/PiwikTracker
Application  terminated.

what do you think about it?? 
Thanks.
have a nice day .

**Comment by Flash3001** [comment]
@domdp16 That is most likely a incompatibility of versions in the library, your Xcode version and the SwiftSupport packages. To work all of them need to match. 

Please take a look at **PiwikTracker** to see what is the latest version of Xcode it support, after that make sure you have the same one in your machine (at least for the machine you use to publish the app). 

The SwiftSupport packages all inform for which version of Xcode it was published for. For instance, if you go to https://www.nuget.org/packages/Xamarin.Swift3.Core/ and take a look at the Release Notes you will see what is the version of Xcode it is supposed to support. The same applies to https://www.nuget.org/packages/Xamarin.Swift4.Core/. 

If the library supports Xcode 9.3 just update everything to the latest versions (including VS4M), otherwise you will need to also check VS4M version.
