### ISSUE TITLE
Are Xamarin.Swift4.* compatible with Linking ?

### ISSUE THREAD

**Issue by rudyspano** [Flash3001/Xamarin.Swift#22]
[TestSwift.zip](https://github.com/Flash3001/Xamarin.Swift3.Support/files/2749203/TestSwift.zip)
Hello,

Thanks for your work. I use your nuget packages in order to make a binding to a Swift Library.
Everything is working.
But we have a blocking issue regarding the size of the ipa generated.
Does the "Link All" feature working with your libraries?
I made some tests with an empty Xamarin Forms app: 8mB in Release.
Adding Xamarin.Swift4.Core and Xamarin.Swift.Foundation increase the size of the generated ipa to 58,8mB with the following Build configuration: Link All, ARM64, LLVM.

Is it normal? Is there any additional thing to configure ?

Find my test project in attachment.

References:
-https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76
-https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos

Thanks

**Comment by Flash3001** [comment]
Hey @rudyspano, unfortunately, it doesn't work. 

When you link your app it removes the code from C# world that your app is not going to use, but the linker has no awareness of these Swift runtime libraries. 

I don't know how the linker works with dynamic libraries (loaded on demand, instead of embedded into your binary), but even if it could do something, like recreate the library, it wouldn't know what to do in this case as these libraries only work because of Objective-C/Swift native relationship. When you use a Swift library your C# code is not talking to Swift, it is talking to Objective-C and then Objective-C is doing its magic to work with Swift.

The only option I can see to shrink the size of these libraries is to remove some architectures from it. If you take libswiftCore.dylib as an example you will see that internally it has code for ARM64, ARMv7 and ARMv7s - x86 and X86-64 are on a separate file - you can remove some of it and it can help reduce file size a bit - for now this is manual work https://github.com/Flash3001/Xamarin.Swift3.Support/commit/5190af914f059b313110fc560bddc62788b6bb3f#diff-f780e613b8e8e935aeb5b88fa6d2a187.

Another thing to keep in mind is: Apple requires you to upload these same files untouched on a SwiftSupport folder inside of your .IPA file (step 7 on the referenced material on your comment). So if the issue is the size of the IPA file it will help, but not a lot.

**Comment by Flash3001** [comment]
Not linking, but the newer version of the library now supports the removal of unneeded architectures from your project, what will help to reduce your upload size. https://www.nuget.org/packages/Xamarin.Swift/

Just to clarify, that is nice to reduce your upload size, but Apple already does App Thinning, so they only send to the final user what their device needs.
