### ISSUE TITLE
XCode 10.2 and Swift 4.2

### ISSUE THREAD

**Issue by SangI762** [Flash3001/Xamarin.Swift#35]
I would like to use external Swift library which is builded on 4.2 Swift version and my app which is builded with XCode 10.2. How I can do this? When I add Swift 4 libraries it works on device, but I can't publish to AppStore, because it reject with ITMS-90428: Invalid Swift Support. If I use 10.1 XCode then everything is ok. (I use auto_package_ipa.sh script for SwiftSupport folder). If I add Xamarin.Swift new nuget package, then my project won't compile and says that installed Swift is 5.0.1, but library requires 4.2. But XCode 10.2 official says that Swift 5.0 compiler can compile Swift 4.2 libraries. So what I can do here? Library is external and can't be recompiled with Swift 5 only for me. Can I take Swift 4.2 libraries from older XCode and put it in SwiftSupport folder when packing ipa with XCode 10.2? How it works?

**Comment by Kingamattack** [comment]
I had a similar issue and I preferred to downgrade my Xcode version to 10.1 which can maximum target Swift 5.0.
And then you can just add Xamarin.Swift to your project instead of tons of Swift4 libs.
You can type swift --version in your terminal to check that you are in Swift 5 and not Swift 5.0.1

**Comment by Flash3001** [comment]
As @Kingamattack mentioned you can downgrade your Xcode version. Unfortunately this is problem for everyone. Now with Swift 5 we have more liberty to upgrade Xcode without having to upgrade libraries, but if it is 4.2 you need to either downgrade your Xcode version or rebuild the library. 

Another option, which is very hacky and I am not sure will actually work is to have 2 separated versions of Xcode installed, branch this project and be sure Xamarin.Swift points to whatever Xcode version (and tools) you want instead of the one pointed by Visual Studio then use the ipa_package_setpath that already allows you to specify a Xcode version.
