### ISSUE TITLE
ITMS-90428: Invalid Swift Support - Payload - The files libswiftCoreGraphics.dylib, libswiftDarwin.dylib, libswiftos.dylib, libswiftQuartzCore.dylib, libswiftFoundation.dylib, libswiftMetal.dylib, libswiftCoreLocation.dylib, libswiftCoreFoundation.dylib, libswiftCoreImage.dylib, libswiftObjectiveC.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftCore.dylib don’t match with the /Payload/MyApp.app/Frameworks/

### ISSUE THREAD

**Issue by amrutha786** [Flash3001/Xamarin.Swift#40]
Lucas, 

I am currently integrating a swift 5.0 library into my visual studio code; 
Xcode 10.2 
Visual Studio for Mac 8.2.5 
Nuget Package : Xamarin.Swift (1.0.2)

I have followed Step #7  in https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76 

used IPA using the script as: sh package_ipa_default.sh AppPath iPaPath

During App Submission All went well until i got an email from Apple as below : 

ITMS-90428: Invalid Swift Support - The files libswiftCoreGraphics.dylib, libswiftDarwin.dylib, libswiftos.dylib, libswiftQuartzCore.dylib, libswiftFoundation.dylib, libswiftMetal.dylib, libswiftCoreLocation.dylib, libswiftCoreFoundation.dylib, libswiftCoreImage.dylib, libswiftObjectiveC.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftCore.dylib don’t match /Payload/MyApp.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/MyApp.app/Frameworks/libswiftDarwin.dylib, /Payload/MyApp.app/Frameworks/libswiftos.dylib, /Payload/MyApp.app/Frameworks/libswiftQuartzCore.dylib, /Payload/MyApp.app/Frameworks/libswiftFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftMetal.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreLocation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreImage.dylib, /Payload/MyApp.app/Frameworks/libswiftObjectiveC.dylib, /Payload/MyApp.app/Frameworks/libswiftUIKit.dylib, /Payload/MyApp.app/Frameworks/libswiftDispatch.dylib, /Payload/MyApp.app/Frameworks/libswiftCore.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/MyApp.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/MyApp.app/Frameworks/libswiftDarwin.dylib, /Payload/MyApp.app/Frameworks/libswiftos.dylib, /Payload/MyApp.app/Frameworks/libswiftQuartzCore.dylib, /Payload/MyApp.app/Frameworks/libswiftFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftMetal.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreLocation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreImage.dylib, /Payload/MyApp.app/Frameworks/libswiftObjectiveC.dylib, /Payload/MyApp.app/Frameworks/libswiftUIKit.dylib, /Payload/MyApp.app/Frameworks/libswiftDispatch.dylib, /Payload/MyApp.app/Frameworks/libswiftCore.dylib.

**Comment by amrutha786** [comment]
Upon checking the Payload folder i noticed that the initial payload has swift dylib files of Version 5.0, but after generated Payload Folder has dylib files of version 4.2.1

**Comment by Kingamattack** [comment]
Maybe an issue with the arm64e architecture
https://stackoverflow.com/questions/53214530/invalid-swift-support-files-dont-match-xcode-10-1

**Comment by nininea1** [comment]
any solutions ?

**Comment by Flash3001** [comment]
This difference in versions can happen if you build your app using the tools of one version of Xcode and run the package script against another version of Xcode. Using either a different machine or having more than 1 copy installed. Both Visual Studio and the scripting package allows you to set the Xcode path to use. The user that created the issue contacted me via Twitter after creating this ticket and they had both Xcode 10.2 and Xcode 10 installed.

**Comment by nininea1** [comment]
I have xcode Version 11.3.1 (11C504) installed , used [package-installer ](https://github.com/Flash3001/ipa-packager)  >> package_ipa_default.sh ... when I go inside 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib , there are two swift folders : swift and swift-5.0 . my vs version is bit older, but I can't really see what the problem is :/ 

packages I use
  <package id="Xamarin.Swift" version="1.0.2" targetFramework="xamarinios10" />
  <package id="iOSCharts" version="3.2.2.1" targetFramework="xamarinios10" />

can you please take a look @Flash3001 ? I got exactly the same email
 
<img width="950" alt="Screen Shot 2020-04-15 at 10 17 53 PM" src="https://user-images.githubusercontent.com/43409661/79372533-f6122f00-7f66-11ea-8b6e-228ecda6b5fc.png">

**Comment by Flash3001** [comment]
@nininea1 please create a new issue. This one might not be related. I saw your comment on https://github.com/Flash3001/iOSCharts.Xamarin/issues/27#issuecomment-613362641 

When creating the new issue please provide information related to that comment, open your .app and see if of the Swift libraries are include in the Frameworks folder in there. As shown by that comment the same files were not copied to the SwiftSupport folder. We need to identify if the problem is when running the package_ipa_default.sh script or when building the targets for Xamarin.Swift
