### ISSUE TITLE
Invalid Swift Support error

### ISSUE THREAD

**Issue by joncortez** [Flash3001/Xamarin.Swift#7]
I am using Xamarin.Swift3.Support Nuget packages on my app and was using the script package_ipa_default.sh to add the SwiftSupport folder into my IPA. I was able to successfully release a couple of times to the AppStore prior to iOS 11 and Xcode 9.

With the latest stable Xamarin release and Xcode 9 installed on my system, I built my IPA using the same process. When I try to upload it to the AppStore, I get an email from Apple saying that the Swift Support libraries do not match the ones in the Payload/MyApp.app/Frameworks/ folder. That makes sense since the files from my Xcode path is newer. I modified the script to copy the files from the Payload/MyApp.app/Frameworks/ folder instead. When I upload this IPA to the AppStore, I get the following email from Apple:

Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftCore.dylib.

Anyone else encountered this issue?

**Comment by Flash3001** [comment]
@joncortez Changing the script to copy from that folder won't work because the files in the SwiftFramework folder can't be signed as the ones in Payload/YourApp.app/Frameworks folder.

Your binding support Swift4? If so remove the Xamarin.Swift3.* packages and upgrade to the Xamarin.Swift4.* ones - pay attention to dependencies as they might have changed, like CoreFoundation.

If not have you can try to download this repo files (as it contains the original files from the Xcode folder) and try to recreate the folder from Xcode 8.3.3. Then change the script to this new location.

Sample https://github.com/Flash3001/Xamarin.Swift3.Support/tree/master/Swift3/Xamarin.Swift3.Core/Frameworks

The structure is different and you will have some work to by moving files if Swift4 isn't an option.

The original Xcode folder is flat and contains all **device** files in the same root directory, this repo always store then individually inside of **Xamarin.Swift3.[PACKAGE]/Frameworks**

**Comment by joncortez** [comment]
I will explore both options. We only have 2 third-party Swift-based framework and only one is closed-source. We might be able to ask the vendor to build with Swift4. Thank you for your quick response @Flash3001.
